/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;
import Aplicacion.*;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VInstalaciones extends javax.swing.JDialog {
    FachadaAplicacion fachadaAp;
    ModeloTablaTrabajadores modTablaTrabajadores;
    ModeloTablaEquipo modTablaEquipos;

    /**
     * Creates new form VInstalaciones
     */
    public VInstalaciones(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fachadaAp = fa;
        modTablaTrabajadores = new ModeloTablaTrabajadores();
        modTablaEquipos = new ModeloTablaEquipo();
        initComponents();
        tablaTrabajadores.setModel(modTablaTrabajadores);
        tablaTrabajadores.setFillsViewportHeight(true);
        tablaEquipo.setModel(modTablaEquipos);
        tablaEquipo.setFillsViewportHeight(true);
        //Lógica para que combobox muestre los id's de las salas existentes
        cargarSalas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloVentana = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSalas = new javax.swing.JPanel();
        labelFraseSala = new javax.swing.JLabel();
        comboBoxSala = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        panelEquipo = new javax.swing.JPanel();
        labelFraseEquipo = new javax.swing.JLabel();
        comboBoxEquipo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEquipo = new javax.swing.JTable();
        botonAnadir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTituloVentana.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTituloVentana.setText("Instalaciones");

        labelFraseSala.setText("Trabajadores asignados a la sala:");

        comboBoxSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSalaActionPerformed(evt);
            }
        });

        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Cargo", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(tablaTrabajadores);

        javax.swing.GroupLayout panelSalasLayout = new javax.swing.GroupLayout(panelSalas);
        panelSalas.setLayout(panelSalasLayout);
        panelSalasLayout.setHorizontalGroup(
            panelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalasLayout.createSequentialGroup()
                .addGroup(panelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSalasLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(labelFraseSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSalasLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelSalasLayout.setVerticalGroup(
            panelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFraseSala)
                    .addComponent(comboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salas", panelSalas);

        labelFraseEquipo.setText("Equipo asignado a la sala:");

        comboBoxEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEquipoActionPerformed(evt);
            }
        });

        tablaEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Modelo"
            }
        ));
        jScrollPane2.setViewportView(tablaEquipo);

        botonAnadir.setText("Añadir");

        botonGuardar.setText("Guardar");

        botonBorrar.setText("Borrar");

        javax.swing.GroupLayout panelEquipoLayout = new javax.swing.GroupLayout(panelEquipo);
        panelEquipo.setLayout(panelEquipoLayout);
        panelEquipoLayout.setHorizontalGroup(
            panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquipoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelEquipoLayout.createSequentialGroup()
                        .addComponent(labelFraseEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelEquipoLayout.setVerticalGroup(
            panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFraseEquipo)
                    .addComponent(comboBoxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquipoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(panelEquipoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(botonAnadir)
                        .addGap(94, 94, 94)
                        .addComponent(botonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBorrar)
                        .addGap(54, 54, 54))))
        );

        jTabbedPane1.addTab("Equipo", panelEquipo);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTituloVentana)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void comboBoxSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSalaActionPerformed
        // TODO add your handling code here:
        String salaSeleccionada = (String) comboBoxSala.getSelectedItem();
        if (salaSeleccionada != null) {
            cargarTrabajadoresSala(salaSeleccionada);
        }
    }//GEN-LAST:event_comboBoxSalaActionPerformed

    private void comboBoxEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEquipoActionPerformed
        // TODO add your handling code here:
        String salaSeleccionada = (String) comboBoxEquipo.getSelectedItem();
        if (salaSeleccionada != null) {
            cargarEquiposSala(salaSeleccionada);
        }
    }//GEN-LAST:event_comboBoxEquipoActionPerformed
    
    private void cargarSalas() {
        List<String> salas = fachadaAp.obtenerSalas(); // Obtener las salas desde la fachada

        comboBoxSala.removeAllItems();
        comboBoxEquipo.removeAllItems();

        for (String sala : salas) {
            comboBoxSala.addItem(sala);
            comboBoxEquipo.addItem(sala);
        }

        // Seleccionar la primera sala por defecto y cargar los datos
        if (!salas.isEmpty()) {
            comboBoxSala.setSelectedIndex(0);
            comboBoxEquipo.setSelectedIndex(0);
            cargarTrabajadoresSala(salas.get(0));
            cargarEquiposSala(salas.get(0));
        }
    }
    
    private void cargarTrabajadoresSala(String idSala) {
        List<Trabajador> trabajadores = fachadaAp.obtenerTrabajadoresSala(idSala); // Obtener trabajadores desde la fachada
        modTablaTrabajadores.setFilas(trabajadores); // Actualizar el modelo de la tabla
    }
    
    private void cargarEquiposSala(String idSala) {
        List<Equipo> equipos = fachadaAp.obtenerEquiposSala(idSala); // Obtener equipos desde la fachada
        modTablaEquipos.setFilas(equipos); // Actualizar el modelo de la tabla
    }
    
    /*
    private void cargarEquiposSala(int idSala) {
    // Obtener los equipos de la sala desde la fachada
        List<Equipo> equipos = fachadaAp.obtenerEquiposSala(idSala);

        // Actualizar el modelo de la tabla
        modTablaEquipos.setFilas(equipos);
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboBoxEquipo;
    private javax.swing.JComboBox<String> comboBoxSala;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelFraseEquipo;
    private javax.swing.JLabel labelFraseSala;
    private javax.swing.JLabel labelTituloVentana;
    private javax.swing.JPanel panelEquipo;
    private javax.swing.JPanel panelSalas;
    private javax.swing.JTable tablaEquipo;
    private javax.swing.JTable tablaTrabajadores;
    // End of variables declaration//GEN-END:variables
}
