/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//esquema a seguir siempre
//ventana --> fa --> gestor --> fbd --> dao


package GUI;
import Aplicacion.*;
import java.time.LocalDate;
import java.util.*;

/**
 *
 * @author alumnogreibd
 */
public class VPrincipal extends javax.swing.JFrame {
    FachadaAplicacion fachadaAp;
    ModeloTablaPeliculas modTablaPeliculas;
    
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal(FachadaAplicacion fa) {
        this.fachadaAp = fa;
        initComponents();
        //Creamos un objeto da clase ModelotablaPeliculas (a nosa plantilla de métodos para unha tabla)
        modTablaPeliculas = new ModeloTablaPeliculas();
        //Seteamos o modelo noso á tabla que temos
        tablaPeliculas.setModel(modTablaPeliculas);
        tablaPeliculas.setFillsViewportHeight(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        textFieldTitulo = new javax.swing.JTextField();
        labelDuracion = new javax.swing.JLabel();
        textFieldDuracion = new javax.swing.JTextField();
        labelIdioma = new javax.swing.JLabel();
        textFieldIdioma = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        textFieldGenero = new javax.swing.JTextField();
        labelFechaEstreno = new javax.swing.JLabel();
        textFieldFechaEstreno = new javax.swing.JTextField();
        labelClasificacion = new javax.swing.JLabel();
        textFieldClasificacion = new javax.swing.JTextField();
        labelDuracionTrailer = new javax.swing.JLabel();
        textFieldDuracionTrailer = new javax.swing.JTextField();
        labelSinopsis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSinopsis = new javax.swing.JTextArea();
        botonBuscar = new javax.swing.JButton();
        botonAnadirEmision = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        botonSalir = new javax.swing.JButton();
        botonAñadir = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        menuItemCartelera = new javax.swing.JMenuItem();
        menuItemRestauracion = new javax.swing.JMenuItem();
        menuItemRRHH = new javax.swing.JMenuItem();
        menuItemInstalaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setText("Título:");

        labelDuracion.setText("Duración:");

        labelIdioma.setText("Idioma:");

        labelGenero.setText("Género:");

        labelFechaEstreno.setText("Fecha estreno:");

        labelClasificacion.setText("Clasificación:");

        labelDuracionTrailer.setText("Duración trailer:");

        labelSinopsis.setText("Sinopsis:");

        textAreaSinopsis.setColumns(20);
        textAreaSinopsis.setRows(5);
        jScrollPane1.setViewportView(textAreaSinopsis);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonAnadirEmision.setText("Añadir emisión");
        botonAnadirEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirEmisionActionPerformed(evt);
            }
        });

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaPeliculas);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        menuAdministracion.setText("Administración cine");
        menuAdministracion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        menuItemCartelera.setText("Cartelera");
        menuItemCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCarteleraActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuItemCartelera);

        menuItemRestauracion.setText("Restauración");
        menuItemRestauracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRestauracionActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuItemRestauracion);

        menuItemRRHH.setText("RR.HH");
        menuItemRRHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRRHHActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuItemRRHH);

        menuItemInstalaciones.setText("Instalaciones");
        menuItemInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInstalacionesActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuItemInstalaciones);

        jMenuBar1.add(menuAdministracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelClasificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelDuracionTrailer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDuracionTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(botonEditar)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonEliminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonSalir))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelDuracion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelIdioma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelFechaEstreno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldFechaEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelSinopsis)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(botonAnadirEmision))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(botonBuscar)))))))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(textFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuracion)
                    .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdioma)
                    .addComponent(textFieldIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClasificacion)
                    .addComponent(textFieldClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGenero)
                    .addComponent(textFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuracionTrailer)
                    .addComponent(textFieldDuracionTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaEstreno)
                    .addComponent(textFieldFechaEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSinopsis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(botonAnadirEmision)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(botonAñadir)
                    .addComponent(botonEditar)
                    .addComponent(botonEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnadirEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirEmisionActionPerformed
        //Dado que temos o modelo noso, collemos o objeto del e obtemos a película i-ésima do array con "obtenerPelicula".
        //desa forma, o i vai ser igual á fila que esté seleccionada na tabla. A tabla ten o noso modelo 
        Pelicula peliculaAnadir = modTablaPeliculas.obtenerPelicula(tablaPeliculas.getSelectedRow());
        
        //Creamos a ventana para añadir unha sesión
        VAnadirSesion vAnadirSesion = new VAnadirSesion(this, true, fachadaAp, peliculaAnadir);
        vAnadirSesion.setVisible(true);
    }//GEN-LAST:event_botonAnadirEmisionActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        //Dado que temos o modelo noso, collemos o objeto del e obtemos a película i-ésima do array con "obtenerPelicula".
        //desa forma, o i vai ser igual á fila que esté seleccionada na tabla. A tabla ten o noso modelo 
        Pelicula peliculaEditar = modTablaPeliculas.obtenerPelicula(tablaPeliculas.getSelectedRow());
        
        //Creamos a ventana de edición
        //if(peliculaEditar != null) {
            VGestionPeliculas vGestPelicula = new VGestionPeliculas(this, true, fachadaAp, peliculaEditar);
            vGestPelicula.setVisible(true);
        //}
        //else {
           // fachadaAp.muestraExcepcion("ERROR. Debes seleccionar una película.");
        //}
    }//GEN-LAST:event_botonEditarActionPerformed
/**
 *
 * MUY IMPORTANTE. os objetos Pelicula, facelos enteirs (non solo almacenar os atributos que se enseñan na tabla).
 * Esto para que, cando vaias a editar unha, para poder pasar esa pelicula como parámetro, con un "obtenerPelicula" sea suficiente.
 * Se non almacenamos todos os atributos, algún pode quedar como null e dar a lata.
 * 
 */
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        List<Pelicula> peliculas = new ArrayList<Pelicula>();

        //Recuperamos todos los textField de la ventana
        String titulo = textFieldTitulo.getText();
        String duracion = textFieldDuracion.getText();
        String genero = textFieldGenero.getText();
        String sinopsis = textAreaSinopsis.getText();
        String clasificacion = textFieldClasificacion.getText();
        String idioma = textFieldIdioma.getText();
        
        //Nos aseguramos de que, en caso de no especificar fecha, no dea error al hacer parse
        String textoFecha = textFieldFechaEstreno.getText().trim();
        LocalDate fechaEstreno = null;
        if (!textoFecha.isEmpty()) {
            fechaEstreno = LocalDate.parse(textoFecha);
        }
        
        String duracionTrailer = textFieldDuracionTrailer.getText();
        
        //Llamamos a la fachada de la aplicación
        peliculas = fachadaAp.buscarPeliculas(titulo, duracion, genero, sinopsis, clasificacion, idioma, fechaEstreno, duracionTrailer);
        
        modTablaPeliculas.setFilas(peliculas);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void menuItemCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCarteleraActionPerformed
        // TODO add your handling code here:
        VCartelera vCartelera;
        
        vCartelera = new VCartelera(this, true, fachadaAp);
        vCartelera.setVisible(true);
    }//GEN-LAST:event_menuItemCarteleraActionPerformed

    private void menuItemRestauracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRestauracionActionPerformed
        VRestauracion vRestauracion;
        
        vRestauracion = new VRestauracion(this, true, fachadaAp);
        vRestauracion.setVisible(true);
    }//GEN-LAST:event_menuItemRestauracionActionPerformed

    private void menuItemRRHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRRHHActionPerformed
        // TODO add your handling code here:
        VRecursosHumanos vRRHH;
        
        vRRHH = new VRecursosHumanos(this, true, fachadaAp);
        vRRHH.setVisible(true);
    }//GEN-LAST:event_menuItemRRHHActionPerformed

    private void menuItemInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInstalacionesActionPerformed
        // TODO add your handling code here:
        VInstalaciones vInstalaciones;
        
        vInstalaciones = new VInstalaciones(this, true, fachadaAp);
        vInstalaciones.setVisible(true);
    }//GEN-LAST:event_menuItemInstalacionesActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int filaSeleccionada = tablaPeliculas.getSelectedRow();

        if (filaSeleccionada == -1) {
            fachadaAp.muestraExcepcion("ERROR. Debes seleccionar una película para eliminar.");
            return;
        }

        Pelicula peliculaEliminar = modTablaPeliculas.obtenerPelicula(filaSeleccionada);

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas eliminar la película '" + peliculaEliminar.getTitulo() + "'?\n" +
                "Se eliminarán también las asociaciones en las tablas Sesion, Valorar y Anuncio.",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            fachadaAp.eliminarPelicula(peliculaEliminar);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadirEmision;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelClasificacion;
    private javax.swing.JLabel labelDuracion;
    private javax.swing.JLabel labelDuracionTrailer;
    private javax.swing.JLabel labelFechaEstreno;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdioma;
    private javax.swing.JLabel labelSinopsis;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenuItem menuItemCartelera;
    private javax.swing.JMenuItem menuItemInstalaciones;
    private javax.swing.JMenuItem menuItemRRHH;
    private javax.swing.JMenuItem menuItemRestauracion;
    private javax.swing.JTable tablaPeliculas;
    private javax.swing.JTextArea textAreaSinopsis;
    private javax.swing.JTextField textFieldClasificacion;
    private javax.swing.JTextField textFieldDuracion;
    private javax.swing.JTextField textFieldDuracionTrailer;
    private javax.swing.JTextField textFieldFechaEstreno;
    private javax.swing.JTextField textFieldGenero;
    private javax.swing.JTextField textFieldIdioma;
    private javax.swing.JTextField textFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
