/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Aplicacion.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class VRecursosHumanos extends javax.swing.JDialog {

    FachadaAplicacion fachadaAp;
    ModeloTablaTrabajadores modTablaTrabajadores;

    /**
     * Creates new form VRecursosHumanos
     */
    public VRecursosHumanos(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fachadaAp = fa;
        modTablaTrabajadores = new ModeloTablaTrabajadores();
        initComponents();
        tablaTrabajadores.setModel(modTablaTrabajadores);
        tablaTrabajadores.setFillsViewportHeight(true);
        //Lógica para coller os valores do enum
    }

    boolean insertarTrabajador = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloVentana = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelDni = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldDNI = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        labelDniDatos = new javax.swing.JLabel();
        labelNombreDatos = new javax.swing.JLabel();
        labelAp1 = new javax.swing.JLabel();
        labelAp2 = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        labelSueldo = new javax.swing.JLabel();
        labelTrabajo = new javax.swing.JLabel();
        labelSala = new javax.swing.JLabel();
        texFieldDniDatos = new javax.swing.JTextField();
        textFieldNombreDatos = new javax.swing.JTextField();
        textFieldAp1 = new javax.swing.JTextField();
        textFieldAp2 = new javax.swing.JTextField();
        textFieldCargo = new javax.swing.JTextField();
        textFieldSueldo = new javax.swing.JTextField();
        comboBoxTrabajo = new javax.swing.JComboBox<>();
        cbSala1 = new javax.swing.JCheckBox();
        cbSala2 = new javax.swing.JCheckBox();
        cbSala3 = new javax.swing.JCheckBox();
        cbSala4 = new javax.swing.JCheckBox();
        cbSala5 = new javax.swing.JCheckBox();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTituloVentana.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTituloVentana.setText("RR.HH");

        labelNombre.setText("Nombre:");

        labelDni.setText("DNI:");

        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cargo", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(tablaTrabajadores);

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        labelDniDatos.setText("DNI:");

        labelNombreDatos.setText("Nombre:");

        labelAp1.setText("Apellido 1:");

        labelAp2.setText("Apellido 2:");

        labelCargo.setText("Cargo:");

        labelSueldo.setText("Sueldo:");

        labelTrabajo.setText("Trabajo:");

        labelSala.setText("Salas:");

        comboBoxTrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza", "Proyeccion" }));
        comboBoxTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTrabajoActionPerformed(evt);
            }
        });

        cbSala1.setText("Sala 1");

        cbSala2.setText("Sala 2");

        cbSala3.setText("Sala 3");

        cbSala4.setText("Sala 4");

        cbSala5.setText("Sala 5");

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloVentana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(labelDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCargo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldCargo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDniDatos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texFieldDniDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNombreDatos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldNombreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSueldo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldSueldo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelAp1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelTrabajo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxTrabajo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(labelSala)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSala3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSala1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbSala4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSala2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbSala5))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(labelAp2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonSalir)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(labelDni)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(botonNuevo)
                        .addGap(94, 94, 94)
                        .addComponent(botonGuardar)
                        .addGap(102, 102, 102)
                        .addComponent(botonEliminar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDniDatos)
                    .addComponent(labelNombreDatos)
                    .addComponent(labelAp1)
                    .addComponent(labelAp2)
                    .addComponent(texFieldDniDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargo)
                    .addComponent(labelSueldo)
                    .addComponent(labelTrabajo)
                    .addComponent(textFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSala1)
                    .addComponent(cbSala4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSala2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelSala)
                        .addComponent(cbSala5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSala3)
                    .addComponent(botonSalir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarDatosTrabajadores(ModeloTablaTrabajadores m) {
        Trabajador trab = m.obtenerTrabajador(tablaTrabajadores.getSelectedRow());

        texFieldDniDatos.setText(m.obtenerTrabajador(tablaTrabajadores.getSelectedRow()).getDni());
        textFieldNombreDatos.setText(m.obtenerTrabajador(tablaTrabajadores.getSelectedRow()).getNombre());
        textFieldAp1.setText(m.obtenerTrabajador(tablaTrabajadores.getSelectedRow()).getApellido1());
        textFieldAp2.setText(m.obtenerTrabajador(tablaTrabajadores.getSelectedRow()).getApellido2());
        textFieldCargo.setText(m.obtenerTrabajador(tablaTrabajadores.getSelectedRow()).getCargo());
        textFieldSueldo.setText(m.obtenerTrabajador(tablaTrabajadores.getSelectedRow()).getSueldo().toString());

        // Obtener el tipo y marcarlo en el comboBox
        String tipo = fachadaAp.obtenerTipoTrabajador(trab.getDni());
        System.out.println("tipo: " + tipo);

        comboBoxTrabajo.setSelectedItem(tipo);

        // Obtener salas y marcar los checkboxes
        List<Integer> salasAsignadas = fachadaAp.obtenerSalasTrabajador(trab.getDni());
        cbSala1.setSelected(salasAsignadas.contains(1));
        cbSala2.setSelected(salasAsignadas.contains(2));
        cbSala3.setSelected(salasAsignadas.contains(3));
        cbSala4.setSelected(salasAsignadas.contains(4));
        cbSala5.setSelected(salasAsignadas.contains(5));

    }

    private void buscarTrabajadores() {
        ModeloTablaTrabajadores m;

        m = (ModeloTablaTrabajadores) tablaTrabajadores.getModel();
        m.setFilas(fachadaAp.obtenerTrabajador(textFieldNombre.getText(), textFieldDNI.getText()));
        if (m.getRowCount() > 0) {
            tablaTrabajadores.setRowSelectionInterval(0, 0);
            //seleccionamos la fila que queremos con getSelectedRow y a partir de que le pasamos ese parámetro a obtenerUsuarios, este busca el usuario a partir del índice
            visualizarDatosTrabajadores(m);
            botonGuardar.setEnabled(true);
            botonEliminar.setEnabled(true);

            // Hacer clic en la lista
            tablaTrabajadores.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    int row = tablaTrabajadores.rowAtPoint(e.getPoint()); // Get clicked row
                    if (row != -1) { // Ensure row is valid
                        int column = tablaTrabajadores.columnAtPoint(e.getPoint());
                        Object value = tablaTrabajadores.getValueAt(row, column);
                        System.out.println("Clicked on row: " + row + ", column: " + column + "\nValue: " + value);

                        ModeloTablaTrabajadores mtu = (ModeloTablaTrabajadores) tablaTrabajadores.getModel();

                        mtu.obtenerTrabajador(tablaTrabajadores.getSelectedRow());
                        visualizarDatosTrabajadores(mtu);
                    }
                }
            });
        } else {
            botonGuardar.setEnabled(false);
            botonEliminar.setEnabled(false);
        }
    }


    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void alerta(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
        insertarTrabajador = true;

        textFieldNombreDatos.setText("");
        textFieldAp1.setText("");
        texFieldDniDatos.setText("");
        textFieldSueldo.setText("");
        textFieldAp2.setText("");
        textFieldCargo.setText("");
        comboBoxTrabajo.setSelectedItem(null);

        texFieldDniDatos.setEditable(true);
        textFieldNombreDatos.setEditable(true);
        textFieldAp1.setEditable(true);
        textFieldAp2.setEditable(true);
        textFieldCargo.setEditable(true);
        textFieldSueldo.setEditable(true);
        comboBoxTrabajo.setEnabled(true);
        comboBoxTrabajo.setEditable(true);
        cbSala1.setEnabled(true);
        cbSala2.setEnabled(true);
        cbSala3.setEnabled(true);
        cbSala4.setEnabled(true);
        cbSala5.setEnabled(true);

        cbSala1.setSelected(false);
        cbSala2.setSelected(false);
        cbSala3.setSelected(false);
        cbSala4.setSelected(false);
        cbSala5.setSelected(false);
        alerta("Rellena los campos para añadir un nuevo usuario", "Info");
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void comboBoxTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTrabajoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        String nombre = textFieldNombreDatos.getText();
        String ap1 = textFieldAp1.getText();
        String dni = texFieldDniDatos.getText();
        Float sueldo = Float.parseFloat(textFieldSueldo.getText());
        String ap2 = textFieldAp2.getText();
        String cargo = textFieldCargo.getText();
        Trabajador trab = new Trabajador(nombre, ap1, ap2, dni, cargo, sueldo);
        String tipo = comboBoxTrabajo.getSelectedItem().toString();
        ArrayList<Integer> salasSeleccionadas = new ArrayList<>();

        ArrayList<Integer> salasNoseleccionadas = new ArrayList<>();

        if (cbSala1.isSelected()) {
            salasSeleccionadas.add(1);
        } else {
            salasNoseleccionadas.add(1);
        }
        if (cbSala2.isSelected()) {
            salasSeleccionadas.add(2);
        } else {
            salasNoseleccionadas.add(2);
        }
        if (cbSala3.isSelected()) {
            salasSeleccionadas.add(3);
        } else {
            salasNoseleccionadas.add(3);
        }
        if (cbSala4.isSelected()) {
            salasSeleccionadas.add(4);
        } else {
            salasNoseleccionadas.add(4);
        }
        if (cbSala5.isSelected()) {
            salasSeleccionadas.add(5);
        } else {
            salasNoseleccionadas.add(5);
        }

        if (insertarTrabajador == false) {
            fachadaAp.actualizarTrabajador(trab, tipo, salasSeleccionadas, salasNoseleccionadas);
            botonBuscar.doClick();
        } else {
            if (nombre == null || nombre.isEmpty()
                    || ap1 == null || ap1.isEmpty()
                    || ap2 == null || ap2.isEmpty()
                    || dni == null || dni.isEmpty()
                    || cargo == null || cargo.isEmpty()
                    || sueldo == null || sueldo.toString().isEmpty()) {

                System.out.println("Nombre: " + nombre);
                System.out.println("Apellido 1: " + ap1);
                System.out.println("Apellido 2: " + ap2);
                System.out.println("DNI: " + dni);
                System.out.println("Cargo: " + cargo);
                System.out.println("Sueldo: " + sueldo);

                alerta("Rellena todos los campos, por favor", "Error");
                return;
            }
            fachadaAp.insertarTrabajador(trab, tipo, salasSeleccionadas);
            botonBuscar.doClick();
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        buscarTrabajadores();
        texFieldDniDatos.setEditable(false);
        textFieldNombreDatos.setEditable(true);
        textFieldAp1.setEditable(true);
        textFieldAp2.setEditable(true);
        textFieldCargo.setEditable(true);
        textFieldSueldo.setEditable(true);
        comboBoxTrabajo.setEnabled(false);
        cbSala1.setEnabled(true);
        cbSala2.setEnabled(true);
        cbSala3.setEnabled(true);
        cbSala4.setEnabled(true);
        cbSala5.setEnabled(true);

        insertarTrabajador = false;
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        String dni = texFieldDniDatos.getText();
        String tipo = comboBoxTrabajo.getSelectedItem().toString();

        fachadaAp.eliminarTrabajador(dni, tipo);
        botonBuscar.doClick();
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JCheckBox cbSala1;
    private javax.swing.JCheckBox cbSala2;
    private javax.swing.JCheckBox cbSala3;
    private javax.swing.JCheckBox cbSala4;
    private javax.swing.JCheckBox cbSala5;
    private javax.swing.JComboBox<String> comboBoxTrabajo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAp1;
    private javax.swing.JLabel labelAp2;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelDniDatos;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreDatos;
    private javax.swing.JLabel labelSala;
    private javax.swing.JLabel labelSueldo;
    private javax.swing.JLabel labelTituloVentana;
    private javax.swing.JLabel labelTrabajo;
    private javax.swing.JTable tablaTrabajadores;
    private javax.swing.JTextField texFieldDniDatos;
    private javax.swing.JTextField textFieldAp1;
    private javax.swing.JTextField textFieldAp2;
    private javax.swing.JTextField textFieldCargo;
    private javax.swing.JTextField textFieldDNI;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNombreDatos;
    private javax.swing.JTextField textFieldSueldo;
    // End of variables declaration//GEN-END:variables
}
